apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: employee-db-secret
  namespace: hrms-development
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: employee-db-secret
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: hrms/development/employee-profile-service
        property: DATABASE_URL

