apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuerName }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: platform-team@acme.example
    privateKeySecretRef:
      name: {{ .Values.issuerName }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingressClassName }}
